language: julia
julia:
    - 0.4.2
    - nightly
notifications:
  slack: phoenixmachina:tUJkltUznVKfynIB7gxtKHbH
  email : false
after_success:
- julia -e 'cd(Pkg.dir("Tlaloc")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
